#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Oct 26 16:54:11 EEST 2022
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim simulator_axi_behav -key {Behavioral:sim_1:Functional:simulator_axi} -tclbatch simulator_axi.tcl -view /home/alex13dumi/Desktop/xpu/xpu.srcs/sim_1/imports/wave_form_config/simulator_16cells_io_2_2.wcfg -log simulate.log"
xsim simulator_axi_behav -key {Behavioral:sim_1:Functional:simulator_axi} -tclbatch simulator_axi.tcl -view /home/alex13dumi/Desktop/xpu/xpu.srcs/sim_1/imports/wave_form_config/simulator_16cells_io_2_2.wcfg -log simulate.log

