@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Oct 20 10:27:24 +0300 2022
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim simulator_axi_behav -key {Behavioral:sim_1:Functional:simulator_axi} -tclbatch simulator_axi.tcl -view C:/0_MAIN/00_pr/005-doctorat/00-low_level/xpu/xpu.srcs/sim_1/imports/wave_form_config/simulator_16cells_io_2_2.wcfg -log simulate.log"
call xsim  simulator_axi_behav -key {Behavioral:sim_1:Functional:simulator_axi} -tclbatch simulator_axi.tcl -view C:/0_MAIN/00_pr/005-doctorat/00-low_level/xpu/xpu.srcs/sim_1/imports/wave_form_config/simulator_16cells_io_2_2.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
