;-------------------------------------------------------------------------------------
;XPU kernel low level library
;
;macro: index indicate the previus line in matrix
;		firstLine is loaded by "ixload"
;		the next lines are generated by increment 
;-------------------------------------------------------------------------------------
macro	generateFullSquareMatrixIX(index) ; "where" is the previous addess
				nop						vload index
				nop						addrstore
				vload $ARRAY_NR_CELLS	ixload
		label1:	vsub 1					ristore 1
				brnz label1				vadd 1
endmacro