;-------------------------------------------------------------------------------------
;XPU kernel low level library
;
;macro: index indicate the previus line in matrix
;		firstLine is the uniform content of the first line
;		the next lines are generated by increment 
;-------------------------------------------------------------------------------------
macro	generateFullSquareMatrix(index, fitstLine) ; "index" is the previous addess
				nop						vload index
				nop						addrstore
				vload $ARRAY_NR_CELLS	vload fitstLine
		label1:	vsub 1					ristore 1
				brnz label1				vadd 1
endmacro