name: Build and publish sdk

on:
  repository_dispatch:
    types: [publish]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      TAG: ${{ github.event.client_payload.TAG }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}/tools/sdk

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build sdk
      env:
        GITHUB_USER: arhacc
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag_number=$(echo "${TAG}" | sed 's/^v//')
        ./gradlew -Ppublish-version="$tag_number" jpackage

    - name: Publish sdk
      env:
        GITHUB_USER: arhacc
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag_number=$(echo "${TAG}" | sed 's/^v//')
        cd build/jpackage
        deb_file="xpu_${tag_number}_amd64.deb"
        sh -c 'mv *amd64.deb '"${deb_file}"' || exit 0'
        shasum -a 256 "${deb_file}" >"${deb_file}.sha256sum"
        gh release upload ${TAG} "${deb_file}"
        gh release upload ${TAG} "${deb_file}.sha256sum"

  build-macos:
    runs-on: macos-latest
    permissions: write-all
    env:
      TAG: ${{ github.event.client_payload.TAG }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}/tools/sdk

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build sdk
      env:
        GITHUB_USER: arhacc
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag_number=$(echo "${TAG}" | sed 's/^v//')
        ./gradlew -Ppublish-version="$tag_number" clean build jpackage

    - name: Publish sdk
      env:
        GITHUB_USER: arhacc
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag_number=$(echo "${TAG}" | sed 's/^v//')
        cd build/jpackage
        dmg_file="xpu_${tag_number}.dmg"
        sh -c 'mv *.dmg '"${dmg_file}"' || exit 0'
        shasum -a 256 "${dmg_file}" >"${dmg_file}.sha256sum"
        gh release upload ${TAG} "${dmg_file}"
        gh release upload ${TAG} "${dmg_file}.sha256sum"

  build-windows:
    runs-on: windows-latest
    permissions: write-all
    env:
      TAG: ${{ github.event.client_payload.TAG }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}/tools/sdk

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build sdk
      env:
        GITHUB_USER: arhacc
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $tag_number = $Env:TAG.substring(1)
        ./gradlew -Ppublish-version="$tag_number" jpackage

    - name: Publish sdk
      env:
        GITHUB_USER: arhacc
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $tag_number = $Env:TAG.substring(1)
        echo build
        $msi_file = "XpuSdk-$tag_number.msi"
        mv *.msi "$msi_file"
        (Get-FileHash -Path "$msi_file").Hash | Out-File "$msi_file.hash"
        gh release upload $Env:TAG "$msi_file"
        gh release upload $Env:TAG "$msi_file.hash"
