name: Build xrt binaries

on:
  repository_dispatch:
    types: [publish]

jobs:
  build:
    runs-on: [self-hosted, linux, x64, vivado]
    permissions: write-all
    env:
      TAG: ${{ github.event.client_payload.TAG }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}/tools/xrt

    steps:
    - uses: actions/checkout@v3
    
    - name: Building dependencies for GNU/Linux x86_64
      run: ./bin/build-deps.sh x86_64-linux-gnu
      
    - name: Building xrt for GNU/Linux x86_64
      run: ./bin/build-xrt.sh x86_64-linux-gnu
      
    - name: Building dependencies for GNU/Linux ARM EABI (hardware float)
      run: ./bin/build-deps.sh arm-linux-gnueabihf
      
    - name: Building xrt for GNU/Linux ARM EABI (hardware float)
      run: ./bin/build-xrt.sh arm-linux-gnueabihf
      
    - name: Publishing xrt for GNU/Linux x86_64
      env:
        GITHUB_USER: arhacc
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd cross-build/xrt/x86_64-linux-gnu/bin
        tar czf xrt-${last_tag_valid}-x86_64-linux-gnu.tar.gz xrt
        shasum -p -a 256 xrt-${TAG}-x86_64-linux-gnu.tar.gz >xrt-${TAG}-x86_64-linux-gnu.tar.gz.sha256sum
        gh release upload ${TAG} xrt-${TAG}-x86_64-linux-gnu.tar.gz
        gh release upload ${TAG} xrt-${TAG}-x86_64-linux-gnu.tar.gz.sha256sum
    
    - name: Publishing xrt for GNU/Linux ARM EABI (hardware float)
      env:
        GITHUB_USER: arhacc
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd cross-build/xrt/arm-linux-gnueabihf/bin
        tar czf xrt-${TAG}-arm-linux-gnueabihf.tar.gz xrt
        shasum -p -a 256 xrt-${TAG}-arm-linux-gnueabihf.tar.gz >xrt-${TAG}-arm-linux-gnueabihf.tar.gz.sha256sum
        gh release upload ${TAG} xrt-${TAG}-arm-linux-gnueabihf.tar.gz
        gh release upload ${TAG} xrt-${TAG}-arm-linux-gnueabihf.tar.gz.sha256sum