name: Build xrt binaries

on:
  repository_dispatch:
    types: [publish]

jobs:
  build:
    runs-on: [self-hosted, linux, x64, vivado]
    permissions: write-all
    defaults:
      run:
        working-directory: ${{ github.workspace }}/tools/xrt

    steps:
    - uses: actions/checkout@v3
    
    - name: Building dependencies for GNU/Linux x86_64
      run: ./bin/build-deps.sh x86_64-linux-gnu
      
    - name: Building xrt for GNU/Linux x86_64
      run: ./bin/build-xrt.sh x86_64-linux-gnu
      
    - name: Building dependencies for GNU/Linux ARM EABI (hardware float)
      run: ./bin/build-deps.sh arm-linux-gnueabihf
      
    - name: Building xrt for GNU/Linux ARM EABI (hardware float)
      run: ./bin/build-xrt.sh arm-linux-gnueabihf
      
    - name: Publishing xrt for GNU/Linux x86_64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        last_tag_pushed=$(git ls-remote --tags origin | awk -F/ '{print $3}' | sort -V | tail -n1)
        last_tag_valid=$(echo "$last_tag_pushed" | sed 's/[^0-9]*$//')
        cd cross-build/xrt/x86_64-linux-gnu/bin
        tar czf xrt-${last_tag_valid}-x86_64-linux-gnu.tar.gz xrt
        sha256sum xrt-${last_tag_valid}-x86_64-linux-gnu.tar.gz >xrt-${last_tag_valid}-x86_64-linux-gnu.tar.gz.sha256sum
        gh release upload $last_tag_valid xrt-${last_tag_valid}-x86_64-linux-gnu.tar.gz
        gh release upload $last_tag_valid xrt-${last_tag_valid}-x86_64-linux-gnu.tar.gz.sha256sum
    
    - name: Publishing xrt for GNU/Linux ARM EABI (hardware float)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        last_tag_pushed=$(git ls-remote --tags origin | awk -F/ '{print $3}' | sort -V | tail -n1)
        last_tag_valid=$(echo "$last_tag_pushed" | sed 's/[^0-9]*$//')
        cd cross-build/xrt/arm-linux-gnueabihf/bin
        tar czf xrt-${last_tag_valid}-arm-linux-gnueabihf.tar.gz xrt
        sha256sum xrt-${last_tag_valid}-arm-linux-gnueabihf.tar.gz >xrt-${last_tag_valid}-arm-linux-gnueabihf.tar.gz.sha256sum
        gh release upload $last_tag_valid xrt-${last_tag_valid}-arm-linux-gnueabihf.tar.gz
        gh release upload $last_tag_valid xrt-${last_tag_valid}-arm-linux-gnueabihf.tar.gz.sha256sum